language: ruby

rvm:
  - 2.3.1

cache: bundler

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script:
  - bin/rake test
  - bundle exec cucumber
